### ISSUE TITLE
Defang host only

### ISSUE THREAD

**Issue by stevechen353** [amikai/defang#1]
Is it possible to defang only the host part? For example, `https://github.com/golang/go/blob/master/README.md` becomes `hxxps://github[.]com/golang/go/blob/master/README.md`, where the `.` in `README.md` remains unchanged?

**Comment by amikai** [comment]
In this case `https://github.com/golang/go/blob/master/README.md` will defang to `hxxps://github[.]com/golang/go/blob/master/README[.]md`.

Obviously, this is a bug. Thank you for reporting.
